language: android
jdk: oraclejdk8
sudo: false
install:
- echo y | android update sdk -u -a -t tools
- echo y | android update sdk -u -a -t platform-tools
- echo y | android update sdk -u -a -t build-tools-26.0.2
- echo y | android update sdk -u -a -t android-25
- echo y | android update sdk -u -a -t extra-android-support
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-25
  - extra-android-support
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - '.+'
script:
- ./gradlew test
